---
title: "R - Scraping/Parsing Data from JSON files"
author: "Aaron Kessler"
execute:
  echo: true
format:
  html:
    self-contained: true
    code-tools: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# cdc dashboard lives here:
# https://covid.cdc.gov/covid-data-tracker/#county-view
# h/t to Matt Stiles for doing this in Python here: 
# https://github.com/stiles/notebooks/blob/master/coronavirus/11-vaccine-counties.ipynb

library(tidyverse)
library(janitor)
library(jsonlite)
options(scipen = 999)
options(stringsAsFactors = FALSE)


```


```{r}
# set the url target for the ajax endpoint
data_url <- "https://covid.cdc.gov/covid-data-tracker/COVIDData/getAjaxData?id=vaccination_county_condensed_data"
```


```{r}
# parse the json
content <- fromJSON(data_url)
```


```{r}
# returns a list
class(content)
```


```{r}
# second element contains our the county dataset 
content[[2]]
```


```{r}
# create dataframe (tibble) from just the second element
content2_df <- as_tibble(content[[2]])
```


```{r}
# take a look at what we have
glimpse(content2_df)
```


```{r}
# clean up column names and create more descriptive df object name
cdc_vaxdata_countylevel <-  content2_df %>% 
  janitor::clean_names()

head(cdc_vaxdata_countylevel)
```


```{r}
# export results to csv
write_csv(cdc_vaxdata_countylevel, "data/cdc_vaxdata_countylevel.csv")

# and rds
saveRDS(cdc_vaxdata_countylevel, "data/cdc_vaxdata_countylevel.rds")

```

